CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(200) NOT NULL,
    email VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
);

CREATE TABLE accounts (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name VARCHAR(50) NOT NULL,
    owner_id INT NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

CREATE TABLE user_account (
    user_account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    account_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

CREATE TABLE expense_type (
    expense_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_type_name VARCHAR(50) NOT NULL
);

CREATE TABLE expenses (
    expense_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_name VARCHAR(100) NOT NULL,
    expense_amount DECIMAL(10,2) NOT NULL,
    expense_type_id INT NOT NULL,
    expense_date DATE NOT NULL,
    date_sequence INT NOT NULL,
    description VARCHAR(200),
    user_id INT NOT NULL,
    account_id INT NOT NULL,
    FOREIGN KEY (expense_type_id) REFERENCES expense_type(expense_type_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);

INSERT INTO users (password, email, first_name, last_name)
VALUES ('$2a$10$5015WXq4HOY0CtDAipZ40epIJSqqOF58mLareYr0fQyqGcfVmQAIO', 'justinlee97@hotmail.com', 'Justin', 'Lee'), 
       ('$2a$10$5015WXq4HOY0CtDAipZ40epIJSqqOF58mLareYr0fQyqGcfVmQAIO', 'cindypzh@gmail.com', 'Cindy', 'Phyu'),
       ('$2a$10$5015WXq4HOY0CtDAipZ40epIJSqqOF58mLareYr0fQyqGcfVmQAIO', 'test1@gmail.com', 'Test', '1'),
       ('$2a$10$5015WXq4HOY0CtDAipZ40epIJSqqOF58mLareYr0fQyqGcfVmQAIO', 'test2@gmail.com', 'Test', '2'),
       ('$2a$10$5015WXq4HOY0CtDAipZ40epIJSqqOF58mLareYr0fQyqGcfVmQAIO', 'test3@gmail.com', 'Test', '3');

INSERT INTO accounts (account_name, owner_id)
VALUES ('Shared account', 1),
('Individual Food Tracker', 1),
('Family account', 1);

INSERT INTO user_account (user_id, account_id) 
VALUES (1, 1),
       (2, 1),
       (1, 2),
       (1, 3);

INSERT INTO expense_type (expense_type_name)
VALUES 
    ('Groceries'),
    ('Utilities'),
    ('Rent/Mortgage'),
    ('Dining Out'),
    ('Transportation'),
    ('Entertainment'),
    ('Health & Fitness'),
    ('Travel'),
    ('Shopping'),
    ('Subscriptions'),
    ('Gifts'),
    ('Home Improvement');

INSERT INTO expenses (expense_name, expense_amount, expense_type_id, expense_date, date_sequence, description, user_id, account_id)
VALUES 
    ('Netflix Subscription', 15.99, 10, '2024-06-27', 1, 'Monthly subscription fee', 2, 1),
    ('Monthly Gym Membership', 50, 7, '2024-06-28', 2, 'Fitness membership for the month', 1, 1),
    ('Weekend Getaway', 350, 8, '2024-07-01', 1, 'Trip to the beach', 2, 1),
    ('Dinner at Italian Bistro', 45, 4, '2024-07-02', 1, 'Dinner with friends', 1, 1),
    ('Home Security System', 200, 12, '2024-07-05', 1, 'Installation of home security system', 1, 1),
    ('New Couch', 600, 9, '2024-07-10', 1, 'Living room furniture', 2, 1),
    ('Electric Bill', 85, 2, '2024-07-12', 1, 'Monthly electricity bill', 1, 1),
    ('Concert Tickets', 120, 6, '2024-07-15', 1, 'Tickets for a live concert', 2, 1),
    ('Birthday Gift for John', 40, 11, '2024-07-17', 1, 'Gift for John’s birthday', 1, 1),
    ('Office Supplies', 60, 1, '2024-07-20', 1, 'Stationery and other supplies', 2, 1);



SELECT setval('accounts_account_id_seq', (SELECT MAX(account_id) FROM accounts)+1);
SELECT setval('expense_type_expense_type_id_seq', (SELECT MAX(expense_type_id) FROM expense_type)+1);
SELECT setval('users_user_id_seq', (SELECT MAX(user_id) FROM users)+1);
SELECT setval('user_account_user_account_id_seq', (SELECT MAX(user_account_id) FROM user_account)+1);
SELECT setval('expenses_expense_id_seq', (SELECT MAX(expense_id) FROM expenses)+1);

